# Generated by Django 3.2.9 on 2021-11-24 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonInfo',
            fields=[
                ('national_num', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('photo_url', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('devolved_state_pkid', models.ForeignKey(blank=True, db_column='devolved_state_pkid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='devolved_state', to='pokemon.pokemoninfo')),
                ('evolved_state_pkid', models.ForeignKey(blank=True, db_column='evolved_state_pkid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='evolved_state', to='pokemon.pokemoninfo')),
            ],
            options={
                'db_table': 'pokemon_info',
            },
        ),
    ]
