# Generated by Django 3.2.9 on 2021-11-25 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemoninfo',
            name='devolved_state_pkid',
            field=models.ForeignKey(blank=True, db_column='devolved_state_pkid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devolved_state', to='pokemon.pokemoninfo'),
        ),
        migrations.AlterField(
            model_name='pokemoninfo',
            name='evolved_state_pkid',
            field=models.ForeignKey(blank=True, db_column='evolved_state_pkid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolved_state', to='pokemon.pokemoninfo'),
        ),
    ]
