# Generated by Django 3.2.9 on 2021-11-25 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_auto_20211125_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moves',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=255)),
                ('element_type', models.CharField(choices=[('normal', 'Normal'), ('fire', 'Fire'), ('water', 'Water'), ('electric', 'Electric'), ('grass', 'Grass'), ('ice', 'Ice'), ('fighting', 'Fighting'), ('poison', 'Poison'), ('ground', 'Ground'), ('flying', 'Flying'), ('psychic', 'Psychic'), ('bug', 'Bug'), ('rock', 'Rock'), ('ghost', 'Ghost'), ('dragon', 'Dragon'), ('dark', 'Dark'), ('steel', 'Steel'), ('fairy', 'Fairy'), ("<class 'pokemon.models.ElementTypes.Meta'>", 'Meta')], max_length=45)),
                ('move_type', models.CharField(choices=[('physical', 'Physical'), ('status', 'Status'), ('special', 'Special'), ("<class 'pokemon.models.MoveTypes.Meta'>", 'Meta')], max_length=45)),
            ],
            options={
                'db_table': 'moves',
            },
        ),
    ]
