# Generated by Django 3.2.9 on 2021-12-02 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0005_gender_region'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gender',
            table='genders',
        ),
        migrations.AlterModelTable(
            name='region',
            table='regions',
        ),
    ]
