# Generated by Django 3.2.9 on 2021-12-02 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0006_auto_20211202_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonWeakness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weakness', models.CharField(choices=[('normal', 'Normal'), ('fire', 'Fire'), ('water', 'Water'), ('electric', 'Electric'), ('grass', 'Grass'), ('ice', 'Ice'), ('fighting', 'Fighting'), ('poison', 'Poison'), ('ground', 'Ground'), ('flying', 'Flying'), ('psychic', 'Psychic'), ('bug', 'Bug'), ('rock', 'Rock'), ('ghost', 'Ghost'), ('dragon', 'Dragon'), ('dark', 'Dark'), ('steel', 'Steel'), ('fairy', 'Fairy'), ('shadow', 'Shadow'), ("<class 'pokemon.models.ElementTypes.Meta'>", 'Meta')], max_length=45)),
                ('pokemon_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.pokemoninfo')),
            ],
            options={
                'db_table': 'pokemon_weaknesses',
                'unique_together': {('weakness', 'pokemon_info')},
            },
        ),
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('normal', 'Normal'), ('fire', 'Fire'), ('water', 'Water'), ('electric', 'Electric'), ('grass', 'Grass'), ('ice', 'Ice'), ('fighting', 'Fighting'), ('poison', 'Poison'), ('ground', 'Ground'), ('flying', 'Flying'), ('psychic', 'Psychic'), ('bug', 'Bug'), ('rock', 'Rock'), ('ghost', 'Ghost'), ('dragon', 'Dragon'), ('dark', 'Dark'), ('steel', 'Steel'), ('fairy', 'Fairy'), ('shadow', 'Shadow'), ("<class 'pokemon.models.ElementTypes.Meta'>", 'Meta')], max_length=45)),
                ('pokemon_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.pokemoninfo')),
            ],
            options={
                'db_table': 'pokemon_types',
                'unique_together': {('type', 'pokemon_info')},
            },
        ),
    ]
