# Generated by Django 3.2.9 on 2021-12-04 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0007_pokemontype_pokemonweakness'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
