# Generated by Django 3.2.9 on 2021-12-06 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0008_delete_pokemonweakness'),
        ('pokemon', '0009_moveentry'),
    ]

    operations = [
    ]
