# Generated by Django 3.2.9 on 2021-12-04 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0008_auto_20211204_1644'),
        ('trainers', '0002_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=45)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown'), ("<class 'pokemon.models.Gender.Meta'>", 'Meta')], max_length=45)),
                ('PokemonInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.pokemoninfo')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainers.teams')),
            ],
            options={
                'db_table': 'pokemon',
            },
        ),
    ]
