# Generated by Django 3.2.9 on 2021-12-04 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0003_pokemon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='PokemonInfo',
            new_name='pokemon_info',
        ),
    ]
