# Generated by Django 3.2.9 on 2021-12-09 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0004_rename_pokemoninfo_pokemon_pokemon_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokedex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('kanto', 'Kanto'), ('johto', 'Johto'), ('hoenn', 'Hoenn'), ('sinnoh', 'Sinnoh'), ('unova', 'Unova'), ('kalos', 'Kalos'), ('alola', 'Alola'), ('galar', 'Galar'), ("<class 'pokemon.models.Region.Meta'>", 'Meta')], max_length=45)),
            ],
            options={
                'db_table': 'pokedex',
            },
        ),
        migrations.AlterField(
            model_name='trainers',
            name='date_of_birth',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
