# Generated by Django 3.2.9 on 2021-12-09 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0004_rename_pokemoninfo_pokemon_pokemon_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainers',
            name='date_of_birth',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
