# Generated by Django 3.2.9 on 2021-12-09 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0005_auto_20211209_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokedex',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainers.trainers'),
        ),
    ]
