# Generated by Django 3.2.9 on 2021-12-09 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0005_alter_trainers_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokedex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('kanto', 'Kanto'), ('johto', 'Johto'), ('hoenn', 'Hoenn'), ('sinnoh', 'Sinnoh'), ('unova', 'Unova'), ('kalos', 'Kalos'), ('alola', 'Alola'), ('galar', 'Galar'), ("<class 'pokemon.models.Region.Meta'>", 'Meta')], max_length=45)),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainers.trainers')),
            ],
            options={
                'db_table': 'pokedex',
            },
        ),
    ]
