# Generated by Django 3.2.9 on 2021-12-13 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0007_auto_20211212_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokedex',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainers.trainers'),
        ),
    ]
