# Generated by Django 3.2.9 on 2021-12-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0009_pokedexentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainers',
            name='date_of_birth',
            field=models.DateTimeField(),
        ),
    ]
